[pytest]
addopts = -v -ra --strict-markers --alluredir=allure-results
testpaths = tests
python_files = *.py

markers =
    smoke: smoke tests
    regression: regression tests
    ui: ui tests
    slow: slow running tests
    spravaSkoly: tests for správa školy
    profil: tests for profil raiditeľa/používateľa
    prihlaskaRiaditel: tests for papierová prihláška vytvorená riaditeľom

filterwarnings =
    ignore::DeprecationWarning