[pytest]
addopts = -v -ra --strict-markers --alluredir=allure-results --html=reports/report.html --self-contained-html
testpaths = tests
python_files = *.py

markers =
    smoke: smoke tests
    regression: regression tests
    retest: for debug
    ui: ui tests
    slow: slow running tests
    spravaSkoly: tests for správa školy
    profil: tests for profil riaditeľa/používateľa
    prihlaskaRiaditel: tests for papierová prihláška vytvorená riaditeľom

filterwarnings =
    ignore::DeprecationWarning