[pytest]
addopts = -v -ra --strict-markers
testpaths = tests
python_files = *.py
; python_classes = Test*
; python_functions = test_*

markers =
    smoke: smoke tests
    regression: regression tests
    ui: ui tests
    slow: slow running tests