import pytest
import os
import re
import utils.data_helper as Data
from utils.helpers import Helper 
from pages.logout_page import LogoutPage
from playwright.sync_api import Page, expect
from pages.login_page import LoginPage
from pages.prihlaska_SS_page import PrihlaskaSS


username=os.getenv("EPRIHLASKY_ZZ_USERNAME")
password=os.getenv("EPRIHLASKY_ZZ_PASSWORD")
username_riad=os.getenv("EPRIHLASKY_RIADITEL_USERNAME")
password_riad=os.getenv("EPRIHLASKY_RIADITEL_PASSWORD")

#get_by_role("button", name="Stredná škola pre AT Pridať").nth(4)

@pytest.mark.regression
def test_prihlaska_na_SS_2kolo(page: Page) -> None:
    data = Data.pop_random_person_from_file("./data/detiSS.txt")
    helper = Helper()
    login = LoginPage(page)
    logout = LogoutPage(page)
    prihlaska = PrihlaskaSS(page)
    login.login_as_zakonny_zastupca(username, password)
    prihlaska.click_on_vytvorit_prihlasku()
    prihlaska.pridat_dieta(data.meno, data.priezvisko, data.rodne_cislo)
    prihlaska.step_1_vyber_ziaka()
    prihlaska.step_2_SVVP()
    prihlaska.step_3_vyber_skoly("pre AT")
    prihlaska.step_4_ZZ()
    prihlaska.step_5_ziak_navsteva_skoly()
    prihlaska.step_6_znamky()
    prihlaska.step_7_sutaze()
    prihlaska.step_8_prilohy()
    #step9
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(re.compile(r"P-2026-.+"))
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("2026/2027")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("-")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("-")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("2. kolo")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(data.meno)
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(data.priezvisko)
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(data.priezvisko)
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(data.rodne_cislo)
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(helper.rc_to_datum_narodenia(data.rodne_cislo))
    if helper.get_pohlavie(data.rodne_cislo) == "ženské":
        pohlavie = "žena"
    else:
        pohlavie = "muž"
    expect(page.locator("#suhrnny-prehlad")).to_contain_text(pohlavie)
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("Slovensko")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("slovenská")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("Slovenská republika")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("slovenský")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("-")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("Narcisová 4/2048, 03845, Myjava, Slovenská republika")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("Nie")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("Nie")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("Nie")
    expect(page.locator("#suhrnny-prehlad")).to_contain_text("ŠVVP")
    expect(page.locator("#skoly")).to_contain_text("1 Stredná škola č. 1")
    expect(page.locator("#skoly")).to_contain_text("910021624")
    expect(page.locator("#skoly")).to_contain_text("Stredná škola pre AT")
    expect(page.locator("#skoly")).to_contain_text("2285H00")
    expect(page.locator("#skoly")).to_contain_text("zlievač -3 ročné")
    expect(page.locator("#skoly")).to_contain_text("Netalentový")
    expect(page.locator("#skoly")).to_contain_text("1. termín")
    expect(page.locator("#skoly")).to_contain_text("slovenský")
    expect(page.locator("#skoly")).to_contain_text("Nie")
    expect(page.locator("#skoly")).to_contain_text("Nie")
    expect(page.locator("#zastupcovia")).to_contain_text("Osobné údaje zákonného zástupcu č. 1")
    expect(page.locator("#zastupcovia")).to_contain_text("Mária")
    expect(page.locator("#zastupcovia")).to_contain_text("Bartošová")
    expect(page.locator("#zastupcovia")).to_contain_text("-")
    expect(page.locator("#zastupcovia")).to_contain_text("855215/3830")
    expect(page.locator("#zastupcovia")).to_contain_text("15.02.1985")
    expect(page.locator("#zastupcovia")).to_contain_text("Mandľová 16/745, 03874, Trenčianska Teplá, Slovenská republika")
    expect(page.locator("#zastupcovia")).to_contain_text("katalontest987@gmail.com")
    expect(page.locator("#zastupcovia")).to_contain_text("+421999888777")
    expect(page.locator("#zastupcovia")).to_contain_text("Osobné údaje zákonného zástupcu č. 2")
    expect(page.locator("#zastupcovia")).to_contain_text("Druhý zákonný zástupca nie je známy.")
    expect(page.locator("#info-o-zs")).to_contain_text("Informácie o základnej škole")
    expect(page.locator("#info-o-zs")).to_contain_text("Zo školy v zahraničí")
    expect(page.locator("#info-o-zs")).to_contain_text("9.")
    expect(page.locator("#info-o-zs")).to_contain_text("9")
    expect(page.locator("#info-o-zs")).to_contain_text("Francúzsky")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("6. ročník (2. polrok)")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("uspokojivé")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("1 - výborný")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("7. ročník (2. polrok)")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("menej uspokojivé")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("3 - dobrý")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("8. ročník (2. polrok)")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("veľmi dobré")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("2 - chválitebný")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("9. ročník (1. polrok)")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("veľmi dobré")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("1 - výborný")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Zumba")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("1. miesto - Školská úroveň")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Umelecké")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Školský rok: 2023/2024")
    expect(page.locator(".prilohaItem").first).to_be_visible()
    expect(page.locator("#prilohyContainer > div:nth-child(2)")).to_be_visible()
    expect(page.locator("#prilohyContainer > div:nth-child(3)")).to_be_visible()
    expect(page.locator("#prilohyContainer > div:nth-child(4)")).to_be_visible()
    expect(page.locator("#prilohyContainer > div:nth-child(5)")).to_be_visible()
    expect(page.locator("#layoutDorucenie")).to_contain_text("Rozhodnutia o prijatí budú zverejnené na elektronickej výveske, o čom budete informovaný e-mailovou správou.")
    prihlaska.click_on_odoslat_prihlasku()
    expect(page.locator("body")).to_contain_text("Chystáte sa odoslať prihlášku na stredné školy, ktoré ste uviedli v prihláške. Po odoslaní prihlášky už nebude možné upravovať údaje ani prílohy, pokiaľ vás na opravu nevyzve riaditeľ školy. Pred odoslaním si preto dôkladne skontrolujte všetky údaje a priložené dokumenty. Odoslaním prihlášky sa formálne začne proces jej posúdenia podľa zákona č. 71/1967 Zb. o správnom konaní (správny poriadok).")
    prihlaska.click_on_potvrdit_odoslanie()
    expect(page).to_have_url(re.compile(r".*/Prihlaska-odoslana.*"), timeout=35000)
    expect(page.locator("h1")).to_contain_text("Prihláška bola úspešne odoslaná!")
    identifikator = page.get_by_text("P-2026-").text_content()
    prihlaska.click_on_prejst_na_prihlasky()
    expect(page).to_have_url(re.compile(r".*/Prihlasky.*"), timeout=35000)
    logout.logout()
    login.login_as_riaditel(username_riad, password_riad, "910021624")
    prihlaska.vyhladanie_prihlasky(data.meno, data.priezvisko)
    expect(page.locator("#sub-riaditel-prihlasky")).to_contain_text(data.priezvisko +" "+data.meno)
    expect(page.locator("#sub-riaditel-prihlasky")).to_contain_text(identifikator)
    expect(page.locator("#sub-riaditel-prihlasky")).to_contain_text("V spracovaní")
