import pytest
import os
import re
import utils.data_helper as Data
from utils.helpers import Helper
from playwright.sync_api import Page, expect
from pages.login_page import LoginPage
from pages.papierova_prihlaska_SS_page import PapierovaPrihlaskaSS

username=os.getenv("EPRIHLASKY_RIADITEL_USERNAME")
password=os.getenv("EPRIHLASKY_RIADITEL_PASSWORD")

@pytest.mark.regres1kolo
@pytest.mark.regres2kolo
def test_pridanie_papierovej_prihlasky_SS(page: Page) -> None:
    data = Data.pop_random_person_from_file("./data/detiSS.txt")
    login = LoginPage(page)
    prihlaska = PapierovaPrihlaskaSS(page)
    helper = Helper()
    den, mesiac, rok = helper.aktualny_datum()
    login.login_as_riaditel(username,password,"910021624")
    prihlaska.click_on_pridaj_prihlasku()
    prihlaska.step_1_osobne_udaje(data.meno, data.priezvisko, data.rodne_cislo)
    prihlaska.step_2_SVVP()
    prihlaska.step_3_vyber_skoly()
    prihlaska.step_4_ZZ()
    prihlaska.step_5_navsteva_ZS()
    prihlaska.step_6_znamky()
    prihlaska.step_7_sutaze()
    prihlaska.step_8_prilohy()
    prihlaska.step_9_ostatne_udaje(den, mesiac, rok)
    #step10 Súhrnný prehľad
    expect(page.locator("#ziadostIdentifikator")).to_contain_text("-")
    expect(page.locator("#ziadostSkolskyRok")).to_contain_text("2026 / 2027")
    expect(page.locator("#ziadostDatumPodania")).to_contain_text(den + "." + mesiac + "." + rok)
    expect(page.locator("#ziadostSposobPodania")).to_contain_text("-")
    expect(page.locator("#poznamkaSkoly")).to_contain_text("*-*")
    expect(page.locator("#koloPrijimaciehoKonania")).to_contain_text("2. kolo")
    expect(page.locator("#dietaMenoSuhrn")).to_contain_text(data.meno)
    expect(page.locator("#dietaPriezviskoSuhrn")).to_contain_text(data.priezvisko)
    expect(page.locator("#dietaRodnePriezviskoSuhrn")).to_contain_text(data.priezvisko)
    expect(page.locator("#dietaRodneCisloSuhrn")).to_contain_text(data.rodne_cislo)
    expect(page.locator("#dietaDatumNarodeniaSuhrn")).to_contain_text(helper.rc_to_datum_narodenia(data.rodne_cislo))
    expect(page.locator("#dietaPohlavieSuhrn")).to_contain_text(helper.get_pohlavie(data.rodne_cislo))
    expect(page.locator("#dietaMiestonarodeniaSuhrn")).to_contain_text("Slovensko")
    expect(page.locator("#dietaNarodnostSuhrn")).to_contain_text("slovenská")
    expect(page.locator("#dietaStatnaPrislusnostSuhrn")).to_contain_text("Slovenská republika")
    expect(page.locator("#dietaMaterinskyJazykSuhrn")).to_contain_text("slovenský")
    expect(page.locator("#dietaInyMaterinskyJazykSuhrn")).to_contain_text("-")
    expect(page.locator("#dietaAdresaTrvalehoPobytuSuhrn")).to_contain_text("Korčekova 12/45, 89516, Palín, Slovenská republika")
    expect(page.locator("#dpZmenenaPracovnaSchopnost")).to_contain_text("Nie")
    expect(page.locator("#dpSVVP")).to_contain_text("Nie")
    expect(page.locator("#dpMentalnePostihnutie")).to_contain_text("Nie")
    expect(page.locator("#dpPoznamka")).to_contain_text("-_-")
    expect(page.locator("#skoly")).to_contain_text("910021624")
    expect(page.locator("#skoly")).to_contain_text("Stredná škola pre AT")
    expect(page.locator("#skoly")).to_contain_text("zlievač -3 ročné")
    expect(page.locator("#skoly")).to_contain_text("Netalentový")
    expect(page.locator("#skoly")).to_contain_text("1. termín")
    expect(page.locator("#skoly")).to_contain_text("slovenský")
    expect(page.locator("#skoly")).to_contain_text("Nie")
    expect(page.locator("#skoly")).to_contain_text("Nie")
    expect(page.locator("#skoly")).to_contain_text("1 Stredná škola č. 1")
    expect(page.locator("#zastupcovia")).to_contain_text("Osobné údaje zákonného zástupcu č. 1")
    expect(page.locator("#zakonnyZastupcaMeno")).to_contain_text("Demeter")
    expect(page.locator("#zakonnyZastupcaPriezvisko")).to_contain_text("Varga")
    expect(page.locator("#zakonnyZastupcaRodnePriezvisko")).to_contain_text("-")
    expect(page.locator("#zakonnyZastupcaRodneCislo")).to_contain_text("840303/7269")
    expect(page.locator("#zastupcovia")).to_contain_text("-")
    expect(page.locator("#zakonnyZastupcaDatumNarodenia")).to_contain_text("03.03.1984")
    expect(page.locator("#zakonnyZastupcaAdresaBydliska")).to_contain_text("Korčekova 12/45, 89516, Palín, Slovenská republika")
    expect(page.locator("#zakonnyZastupcaEmail")).to_contain_text("katalontest987@gmail.com")
    expect(page.locator("#zakonnyZastupcaTelefon")).to_contain_text("+421963258741")
    expect(page.locator("#zastupcovia")).to_contain_text("Osobné údaje zákonného zástupcu č. 2")
    expect(page.locator("#zastupcovia")).to_contain_text("Druhý zákonný zástupca nie je známy.")
    expect(page.locator("#prichodZiakaSuhrnZiadost")).to_contain_text("Zo ZŠ na Slovensku")
    expect(page.locator("#eduidZSSuhrnZiadost")).to_contain_text("910021625")
    expect(page.locator("#nazovZSSuhrnZiadost")).to_contain_text("Základná škola pre AT")
    expect(page.locator("#rocnikSuhrnZiadost")).to_contain_text("9.")
    expect(page.locator("#triedaSuhrnZiadost")).to_contain_text("9.A")
    expect(page.locator("#rokSkolskejDochadzkySuhrnZiadost")).to_contain_text("9")
    expect(page.locator("#vyucovaciJazykVZSSuhrnZiadost")).to_contain_text("Slovenský")
    expect(page.locator("#vysledky-vzdelavania-suhrn")).to_contain_text("6.ročník (2. polrok) Správanie veľmi dobré 7.ročník (2. polrok) Správanie uspokojivé 8.ročník (2. polrok) Správanie menej uspokojivé 9.ročník (1. polrok) Správanie veľmi dobré")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Súťaž")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Preteky v kosení")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("2. miesto - Krajská úroveň")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Súťaže zručnosti")
    expect(page.locator("#sutaze-suhrn")).to_contain_text("Školský rok: 2024/2025")
    expect(page.locator(".prilohaItem")).to_be_visible()
    prihlaska.click_on_odoslat_prihlasku()
    expect(page).to_have_url(re.compile(r".*/Riaditel.*"), timeout=25000)
    expect(page.locator("#riaditel-home-page")).to_contain_text("Prihlášku pre dieťa ste úspešne pridali.")
    prihlaska.najdi_prihlasku(data.meno, data.priezvisko)
    expect(page.locator("#sub-riaditel-prihlasky")).to_contain_text(data.priezvisko+" "+data.meno)
    expect(page.locator("#sub-riaditel-prihlasky")).to_contain_text("V spracovaní")
    prihlaska.click_on_zobrazit_prihlasku()
    expect(page.locator("#detail-prihlasky-riad-SS-content")).to_contain_text("Papierovo")
    expect(page.locator("#detail-prihlasky-riad-SS-content")).to_contain_text("2. kolo")
