import os
import re
from playwright.sync_api import Page, expect
from pages.login_page import LoginPage
from pages.logout_page import LogoutPage
from pages.verejna_zona_page import VerejnaZona
from pages.sprava_skoly_page import SpravaSkoly


username=os.getenv("EPRIHLASKY_RIADITEL_USERNAME")
password=os.getenv("EPRIHLASKY_RIADITEL_PASSWORD")

def test_profil_skoly_SS(page: Page) -> None:
    login_page = LoginPage(page)
    logout_page = LogoutPage(page)
    verejna_zona = VerejnaZona(page)
    sprava_skoly = SpravaSkoly(page)
    login_page.login_as_riaditel(username, password, "910021624")
    sprava_skoly.click_on_menu_sprava_skoly()
    page.get_by_label("Úplná debarierizácia všetkých priestorov a vonkajšieho areálu").click()
    page.get_by_label("Bez telocvične").click()
    page.get_by_label("Multifunkčné vonkajšie ihrisko").click()
    page.locator("#radioGroup-SS_DigR_option_0").click()
    page.locator("#radioGroup-SS_WiFi_option_1").check()
    page.get_by_role("textbox", name="Krátky popis školy").fill("testovací popis 1")
    sprava_skoly.click_on_ulozit_zmeny()
    expect(page.locator("#sprava-skoly-content")).to_contain_text("Údaje profilu školy boli úspešne uložené")
    logout_page.logout()
    verejna_zona.vyhladaj_skolu("Stredná škola pre AT", "910021624", "Stredné školy")
    verejna_zona.click_on_profil_skoly()
    expect(page.locator("#najst-skolu-content")).to_contain_text("Stredná škola pre AT")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Lumpová 11/4, 08796, Žilina")
    expect(page.locator("#najst-skolu-content")).to_contain_text("testovací popis 1")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Úplná debarierizácia všetkých priestorov a vonkajšieho areálu")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Bez telocvične")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Multifunkčné vonkajšie ihrisko")
    expect(page.get_by_text("check").first).to_be_visible()
    expect(page.locator("div[class='category'] div:nth-child(3) span:nth-child(1)")).to_be_visible()
    expect(page.locator("div:nth-child(4) > .material-icons")).to_be_visible()
    expect(page.locator("div:nth-child(5) > .material-icons")).to_be_visible()
    expect(page.locator("div:nth-child(6) > .material-icons")).to_be_visible()
    expect(page.locator("#najst-skolu-content")).to_contain_text("Nie")
    page.get_by_role("button", name="Zavrieť").click()
    login_page.login_as_riaditel(username, password, "910021624")
    sprava_skoly.click_on_menu_sprava_skoly()
    page.locator("#radioGroup-SS_DebS_option_1").click()
    page.get_by_label("Viac telocviční").click()
    page.get_by_label("Viaceré multifunkčné vonkajšie ihriská, bežecká dráha").click()
    page.locator("#radioGroup-SS_DigR_option_4").click()
    page.locator("#radioGroup-SS_WiFi_option_0").check()
    page.get_by_role("textbox", name="Krátky popis školy").fill("testovací popis 2")
    sprava_skoly.click_on_ulozit_zmeny()
    expect(page.locator("#sprava-skoly-content")).to_contain_text("Údaje profilu školy boli úspešne uložené")
    logout_page.logout()
    verejna_zona.vyhladaj_skolu("Stredná škola pre AT", "910021624", "Stredné školy")
    verejna_zona.click_on_profil_skoly()
    expect(page.locator("#najst-skolu-content")).to_contain_text("Stredná škola pre AT")
    expect(page.locator("#najst-skolu-content")).to_contain_text("testovací popis 2")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Prístupné prízemie")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Viac telocviční")
    expect(page.locator("#najst-skolu-content")).to_contain_text("Viaceré multifunkčné vonkajšie ihriská, bežecká dráha")
    expect(page.get_by_text("check").first).to_be_visible()
    expect(page.get_by_text("check").nth(1)).to_be_visible()
    expect(page.get_by_text("check").nth(2)).to_be_visible()
    expect(page.get_by_text("check").nth(3)).to_be_visible()
    expect(page.get_by_text("check").nth(4)).to_be_visible()
    expect(page.locator("#najst-skolu-content")).to_contain_text("Áno")
